name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [11]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Compile Library
        run: ./gradlew :lib:assemble

      - name: Run Paparazzi Tests
        run: ./gradlew :android-lib:testDebugUnitTest
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: liberica-${{matrix.os}}
          path: |
            sample/build/*
            sample/out/*

