name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java-version: [21]

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Library Tests
        run: ./gradlew :lib:test

      - name: Run Paparazzi Compatibility Tests
        run: ./gradlew :lib:testPaparazziCompatAll

      - name: Run Gradle Plugin Unit Tests
        run: ./gradlew :gradle-plugin:test

      - name: Run Gradle Plugin Functional Tests
        run: ./gradlew :gradle-plugin:functionalTest

      - name: Compile Android Library
        run: ./gradlew :android-library:testDebugUnitTest
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_TMP_KEY }}

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{matrix.os}}-${{matrix.java-version}}
          path: |
            lib/build/reports/tests/
            gradle-plugin/build/reports/tests/
